/**
 * 2026 最新 AI 模型权威配置库 (包含腾讯 Hy3 / Hunyuan-T1 与百度 ERNIE 5.1 / ERNIE 5.0 全模型)
 */
export interface LLMModelConfig {
  provider: string;
  name: string;
  modelId: string;
  version: string;
  category: 'text' | 'image' | 'video';
  maxTokens: number;
  contextWindow: number;
  supportsStreaming: boolean;
  supportsFunctionCalling: boolean;
  pricing: { input: number; output: number };
  capabilities: string[];
  recommended: boolean;
}

export interface LLMModels {
  [key: string]: LLMModelConfig;
}

export const LLM_MODELS: LLMModels = {
  // ===== 📝 腾讯混元 (Tencent Hunyuan 2026 最新 Hy3 & T1) =====
  TENCENT_HY3: {
    provider: 'tencent',
    name: '腾讯混元 Hy3 (hy3 官方 2026 最新)',
    modelId: 'hy3',
    version: 'Hy3-2026',
    category: 'text',
    maxTokens: 16384,
    contextWindow: 256000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    pricing: { input: 0.005, output: 0.015 },
    capabilities: ['text', 'code', 'scriptwriting', '256k-context', 'chinese-narrative'],
    recommended: true,
  },
  TENCENT_HUNYUAN_T1: {
    provider: 'tencent',
    name: '腾讯混元 Hunyuan-T1 (t1 官方深度推理)',
    modelId: 'hunyuan-t1-latest',
    version: 'T1-2026',
    category: 'text',
    maxTokens: 8192,
    contextWindow: 128000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    pricing: { input: 0.008, output: 0.024 },
    capabilities: ['text', 'code', 'deep-reasoning', 'cot-logic', 'hybrid-moe'],
    recommended: true,
  },

  // ===== 📝 百度文心一言 (Baidu ERNIE 2026 最新 5.1 / 5.0) =====
  BAIDU_ERNIE_51: {
    provider: 'baidu',
    name: '文心一言 ERNIE 5.1 (2026.05 最新旗舰)',
    modelId: 'ERNIE-5.1',
    version: '5.1-2026',
    category: 'text',
    maxTokens: 16384,
    contextWindow: 500000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    pricing: { input: 0.005, output: 0.015 },
    capabilities: ['text', 'code', 'agentic-reasoning', 'knowledge-qa', 'scriptwriting'],
    recommended: true,
  },
  BAIDU_ERNIE_50: {
    provider: 'baidu',
    name: '文心一言 ERNIE 5.0 (2.4万亿原生全模态)',
    modelId: 'ERNIE-5.0',
    version: '5.0-2026',
    category: 'text',
    maxTokens: 16384,
    contextWindow: 500000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    pricing: { input: 0.008, output: 0.024 },
    capabilities: ['text', 'image', 'video', 'multimodal-native', 'all-in-one'],
    recommended: true,
  },
  BAIDU_ERNIE_45_TURBO: {
    provider: 'baidu',
    name: '文心一言 ERNIE-4.5-Turbo-128K (长文本)',
    modelId: 'ERNIE-4.5-Turbo-128K',
    version: '4.5-Turbo',
    category: 'text',
    maxTokens: 8192,
    contextWindow: 128000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    pricing: { input: 0.002, output: 0.006 },
    capabilities: ['text', 'analysis', '128k-context', 'long-novel-reading'],
    recommended: false,
  },

  // ===== 📝 阿里通义千问 / DeepSeek / Kimi / OpenAI / Claude / Gemini / 智谱 =====
  QWEN_38_MAX: {
    provider: 'alibaba',
    name: 'Qwen 3.8-Max (2026.08 最新)',
    modelId: 'qwen-3.8-max',
    version: '2026.08',
    category: 'text',
    maxTokens: 16384,
    contextWindow: 1000000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    pricing: { input: 0.005, output: 0.015 },
    capabilities: ['text', 'code', 'analysis', 'creative', '1m-context'],
    recommended: true,
  },
  DEEPSEEK_V4_FLASH: {
    provider: 'deepseek',
    name: 'DeepSeek-V4-Flash (2026.07.31 最新)',
    modelId: 'deepseek-v4-flash-0731',
    version: '2026.07.31',
    category: 'text',
    maxTokens: 8192,
    contextWindow: 500000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    pricing: { input: 0.0015, output: 0.006 },
    capabilities: ['text', 'code', 'script-decomposition', 'high-efficiency'],
    recommended: true,
  },
  DEEPSEEK_R1: {
    provider: 'deepseek',
    name: 'DeepSeek-R1 (deepseek-reasoner 官方)',
    modelId: 'deepseek-reasoner',
    version: 'R1',
    category: 'text',
    maxTokens: 8192,
    contextWindow: 64000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    pricing: { input: 0.004, output: 0.016 },
    capabilities: ['text', 'code', 'deep-reasoning', 'cot-logic'],
    recommended: true,
  },
  KIMI_K3: {
    provider: 'moonshot',
    name: 'Kimi K3 (2.8T MoE 2026.07 最新)',
    modelId: 'kimi-k3',
    version: '2026.07',
    category: 'text',
    maxTokens: 16384,
    contextWindow: 1000000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    pricing: { input: 0.008, output: 0.024 },
    capabilities: ['text', 'analysis', 'novel-reading', '1m-context'],
    recommended: true,
  },
  OPENAI_GPT56_SOL: {
    provider: 'openai',
    name: 'GPT-5.6 Sol (2026.07 最新)',
    modelId: 'gpt-5.6-sol',
    version: '2026.07',
    category: 'text',
    maxTokens: 16384,
    contextWindow: 1000000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    pricing: { input: 0.015, output: 0.045 },
    capabilities: ['text', 'code', 'deep-reasoning', 'script-direction'],
    recommended: true,
  },
  CLAUDE_OPUS_5: {
    provider: 'anthropic',
    name: 'Claude Opus 5 (2026.07 最新)',
    modelId: 'claude-opus-5',
    version: '2026.07',
    category: 'text',
    maxTokens: 16384,
    contextWindow: 1000000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    pricing: { input: 0.02, output: 0.06 },
    capabilities: ['text', 'code', 'script-polishing', 'agentic-reasoning'],
    recommended: true,
  },
  GEMINI_36_FLASH: {
    provider: 'google',
    name: 'Gemini 3.6 Flash (200万Context 2026.07)',
    modelId: 'gemini-3.6-flash',
    version: '2026.07',
    category: 'text',
    maxTokens: 16384,
    contextWindow: 2000000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    pricing: { input: 0.00035, output: 0.00105 },
    capabilities: ['text', 'analysis', '2m-context', 'full-book-reading'],
    recommended: true,
  },
  IFLYTEK_SPARK_V4: {
    provider: 'iflytek',
    name: '讯飞星火 Spark V4.0 (generalv4.0 官方)',
    modelId: 'generalv4.0',
    version: 'v4.0',
    category: 'text',
    maxTokens: 8192,
    contextWindow: 500000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    pricing: { input: 0.003, output: 0.01 },
    capabilities: ['text', 'analysis', 'scriptwriting', 'dialogue-simulation'],
    recommended: true,
  },
  ZHIPU_GLM_52: {
    provider: 'zhipu',
    name: 'GLM-5.2 (2026.06 最新)',
    modelId: 'glm-5.2',
    version: '5.2',
    category: 'text',
    maxTokens: 8192,
    contextWindow: 1000000,
    supportsStreaming: true,
    supportsFunctionCalling: true,
    pricing: { input: 0.004, output: 0.012 },
    capabilities: ['text', 'code', 'agentic-coding', 'script-decomposition'],
    recommended: true,
  },

  // ===== 🎨 图片模型 (Image Models) =====
  SEEDREAM_50: {
    provider: 'bytedance',
    name: '字节 Seedream 5.0 (2026.07 高精生图)',
    modelId: 'doubao-seedream-5.0',
    version: '2026.07',
    category: 'image',
    maxTokens: 4096,
    contextWindow: 4096,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    pricing: { input: 0.02, output: 0.08 },
    capabilities: ['image', 'manga-style', 'face-lock', '4k-resolution'],
    recommended: true,
  },
  COGVIEW_4_PRO: {
    provider: 'zhipu',
    name: '智谱 CogView-4 Pro (2026.07 旗舰生图)',
    modelId: 'cogview-4-pro',
    version: '2026.07',
    category: 'image',
    maxTokens: 4096,
    contextWindow: 4096,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    pricing: { input: 0.015, output: 0.06 },
    capabilities: ['image', 'chinese-prompt', 'cyberpunk', 'xianxia-style'],
    recommended: true,
  },
  KLING_IMAGE_25: {
    provider: 'kling',
    name: '可灵 Image V2.5 (2026.07 漫画分镜)',
    modelId: 'kling-image-v2.5',
    version: '2026.07',
    category: 'image',
    maxTokens: 4096,
    contextWindow: 4096,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    pricing: { input: 0.018, output: 0.07 },
    capabilities: ['image', 'storyboard-grid', 'shot-framing', 'multi-character'],
    recommended: true,
  },

  // ===== 🎬 视频模型 (Video Models) =====
  KLING_30_OMNI: {
    provider: 'kling',
    name: '可灵 3.0 Omni (2026.07.31 4K 60fps)',
    modelId: 'kling-3.0-omni',
    version: '2026.07.31',
    category: 'video',
    maxTokens: 4096,
    contextWindow: 4096,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    pricing: { input: 0.03, output: 0.15 },
    capabilities: ['video', '4k-60fps', 'physics-simulation', 'pan-zoom'],
    recommended: true,
  },
  SEEDANCE_25: {
    provider: 'bytedance',
    name: '字节 Seedance 2.5 (2026.07.31 30秒视听)',
    modelId: 'seedance-2.5',
    version: '2026.07.31',
    category: 'video',
    maxTokens: 4096,
    contextWindow: 4096,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    pricing: { input: 0.04, output: 0.18 },
    capabilities: ['video', '30s-continuous', 'asset-control', 'timestamp-edit'],
    recommended: true,
  },
  MINIMAX_H3: {
    provider: 'minimax',
    name: 'MiniMax H3 (2026.07.31 原生双声道)',
    modelId: 'minimax-h3',
    version: '2026.07.31',
    category: 'video',
    maxTokens: 4096,
    contextWindow: 4096,
    supportsStreaming: false,
    supportsFunctionCalling: false,
    pricing: { input: 0.02, output: 0.1 },
    capabilities: ['video', '15s-2k', 'stereo-audio', 'audio-video-sync'],
    recommended: true,
  },
} as const;

export const DEFAULT_LLM_MODEL = LLM_MODELS.TENCENT_HY3 || LLM_MODELS.BAIDU_ERNIE_51;

export const MODEL_RECOMMENDATIONS = {
  textGeneration: [
    LLM_MODELS.TENCENT_HY3,
    LLM_MODELS.BAIDU_ERNIE_51,
    LLM_MODELS.QWEN_38_MAX,
    LLM_MODELS.DEEPSEEK_V4_FLASH,
  ],
  imageGeneration: [LLM_MODELS.SEEDREAM_50, LLM_MODELS.COGVIEW_4_PRO, LLM_MODELS.KLING_IMAGE_25],
  videoGeneration: [LLM_MODELS.KLING_30_OMNI, LLM_MODELS.SEEDANCE_25, LLM_MODELS.MINIMAX_H3],
} as const;
